### ISSUE TITLE
"Use Keras to transfer image style.ipynb" training fails

### ISSUE THREAD

**Issue by philippe-gregoire** [IBM/watson-machine-learning-samples#15]
In "Use Keras to transfer image style.ipynb", the training fails because the data and result buckets are swapped.
The job setup should swap their usage of buckets[0] and buckets[1] to fix the problem

**Comment by JanSoltysik** [comment]
Already done in the private repository, I will add this fix to this repo when our second issue will be ready.

**Comment by JanSoltysik** [comment]
Change pushed to this repo as well.
